package com.microservices.product_service.category.entity;

public enum CategoryType {
    LAPTOPS,
    DESKTOPS,
    TABLETS,
    MONITORS,

    SMARTPHONES,
    PHONE_ACCESSORIES,

    TELEVISIONS,
    HEADPHONES,
    SPEAKERS,
    SOUND_SYSTEMS,

    GAMING_CONSOLES,
    VIDEO_GAMES,
    GAMING_ACCESSORIES,

    CAMERAS,
    LENSES,
    DRONES,
    ACTION_CAMERAS,
    SMART_WATCHES,
    FITNESS_BANDS,

    PROCESSORS,
    GRAPHICS_CARDS,
    MOTHERBOARDS,
    STORAGE,
    RAM,
    COMPUTER_CASES,
    POWER_SUPPLIES,

    MOUSE_AND_KEYBOARDS,
    PRINTERS_AND_SCANNERS,
    NETWORKING,

    SMART_HOME,
    HOME_APPLIANCES,
    KITCHEN_APPLIANCES,
    PERSONAL_CARE,

    CABLES_AND_ADAPTERS,
    OFFICE_SUPPLIES,
    OTHER
}
